import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    patient_name: '',
    patient_age: '',
    patient_gender: 'Male',
    sexual_orientation: '',
    education_bg: '',
    occupation: '',
    marital_status: '',
    economic_status: '',
    religion: '',
    informant: '',
    residential_address: '',
    living_arrangements: '',
    family_structure: '',
    cultural_identity: '',
    language1: '',
    language2: '',
    admission_no: '',
    date: '',
    chief_complaint: '',
    onset_duration: '',
    nature_symptoms: '',
    severity: '',
    course_type: '',
    nature_illness: '',
    identify_trigger: '',
    life_changes: '',
    biological: '',
    psychological: '',
    social_environment: '',
    history_presenting: '',
    mood_affect: [],
    though_content: [],
    though_process: [],
    perception: [],
    behavioural_changes: [],
    sleep_patterns: [],
    energy_level: '',
    appetite_weight: '',
    occupation_academic: '',
    interpersonal_relationship: '',
    selfCare_activity: '',
    recreation_activity: '',
    psychiatric_diagnoses: '',
    treatment_history: '',
    medications: '',
    dosage: '',
    adherence: '',
    sideEffect: '',
    experience_reaction: '',
    hospitalisation_reason: '',
    duration: '',
    crisis_episodes: '',
    fm_mentalHealth: '',
    significant_life: '',
    chronic_stressors: '',
    other_exploration: '',
    other_legalEnvironment: '',
    trauma_exploration: [],
    legal_environment: [],
    disability_status: '',
    chronic_medical: '',
    acute_health: '',
    medication: '',
    medication_allergies: '',
    other_allergy: [],
    significant_medical: [],
    traumatic_injuries: '',
    sexual_health: [],
    family_composition: [],
    family_dynamics: [],
    marriage_type: '',
    family_history: '',
    genetic_predisposition: '',
    family_changes: [],
    family_substance: '',
    family_relationship: '',
    socialCircle_relationship: '',
    relationship_significant: '',
    living_arrangements: '',
    education_bg: '',
    currentEmp_status: '',
    socialRecreation_activity: '',
    social_outlets: '',
    socialMed_engagement: '',
    technology_related: '',
    prenatal_factors: '',
    birth_details: '',
    birth_order: '',
    siblings_number: '',
    bonding_attachment: '',
    milestones_development: '',
    childhood_illness: '',
    siblings_relationship: '',
    parenting_style: '',
    learning_challenge: '',
    pubertal_development: '',
    substance_use: '',
    age_onset: '',
    frequency: '',
    quantity: '',
    motivation_use: '',
    environmental_trigger: '',
    impact_occupation: '',
    impact_interpersonal: '',
    financial_consequences: '',
    craving_intensity: '',
    previous_treatment: '',
    relapse_history: '',
    suicide_history: '',
    triggers_stressors: '',
    homicidal_ideation: '',
    target_method: '',
    immediate_threat: '',
    emergency_response: '',
    hospital_required: '',
};

const psychiatricSlice = createSlice({
    name: 'admission',
    initialState,
    reducers: {
        setField(state, { payload: { field, value } }) {
            state[field] = value;
        },
        resetAll() {
            return initialState;
        },
    },
});

export const { setField, resetAll } = psychiatricSlice.actions;
export default psychiatricSlice.reducer;
